# Generated by Django 3.0.6 on 2020-06-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(max_length=30)),
                ('prod_description', models.CharField(max_length=100)),
                ('prod_price', models.IntegerField()),
                ('prod_category', models.CharField(blank=True, max_length=20)),
                ('prod_publish_date', models.DateField()),
                ('prod_image', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
